export const settlementCopy = {
  en: {
    financeControl: 'PMS financial control', overview: 'Overview', charges: 'Charges', payments: 'Payments', deposits: 'Deposits', periods: 'Financial periods', reconciliation: 'Reconciliation', records: 'Records',
    statements: 'Owner statements', payouts: 'Owner payouts', statementDescription: 'Prepare, review, approve, publish, and revise immutable owner financial snapshots.', payoutDescription: 'Prepare owner payouts from published statements and record evidence-backed submission and results.',
    loading: 'Loading finance records…', error: 'The owner settlement workspace could not be loaded.', noRecords: 'No records match the current filters.', permission: 'Accounting management permission is required for workflow actions.',
    createStatement: 'Prepare owner statement', createPayout: 'Prepare payout batch', search: 'Search', all: 'All', actions: 'Actions', status: 'Status', currency: 'Currency', property: 'Property', owner: 'Owner', sort: 'Sort', apply: 'Apply filters', clear: 'Clear', previous: 'Previous', next: 'Next', pageOf: 'of',
    period: 'Period', revision: 'Revision', payoutNumber: 'Payout batch', opening: 'Opening balance', income: 'Income', expenses: 'Expenses', adjustments: 'Adjustments', closing: 'Closing balance', amount: 'Amount', documents: 'Supporting documents', history: 'Audit timeline', createdBy: 'Prepared by', approvedBy: 'Approved by', publishedBy: 'Published by', paidBy: 'Result recorded by', createdDate: 'Prepared', approvalDate: 'Approved', publicationDate: 'Published', submissionDate: 'Submitted', paidDate: 'Paid',
    month: 'Statement month', ownerReference: 'Owner reference', notes: 'Notes', managementFee: 'Management fee', reserve: 'Reserve', selectStatements: 'Published statements', save: 'Save', cancel: 'Cancel', close: 'Close', upload: 'Upload evidence', documentTitle: 'Document title', file: 'File',
    submitReview: 'Submit for review', approve: 'Approve', publish: 'Publish', void: 'Void', createRevision: 'Create revision', approvePayout: 'Approve payout', submitPayout: 'Submit payout', recordPaid: 'Record paid result', recordFailed: 'Record failed result', retry: 'Retry from draft', cancelPayout: 'Cancel payout', reason: 'Reason', payoutReference: 'External payout reference', evidenceNote: 'Payment-method evidence note', providerConfirmed: 'The payout adapter confirmed submission', evidenceDocument: 'Evidence document',
    makerCheckerStatement: 'The statement generator cannot approve it, and its approver cannot publish it.', makerCheckerPayout: 'The payout preparer cannot approve it, and its approver cannot submit it.', publishReadiness: 'Publication requires a closed matching period and at least one active supporting document.', paidReadiness: 'A paid result requires a new linked evidence document recorded after submission.', immutable: 'Published snapshots and approved payout composition are immutable. Corrections use void-and-revision or payout retry workflows.',
    noDocuments: 'No supporting documents are linked.', noHistory: 'No audit events have been recorded.', noPublishedStatements: 'No eligible published owner statements are available for this owner.', linkedPayouts: 'Linked payout batches',
    sortPeriodLatest: 'Period: latest first', sortPeriodEarliest: 'Period: earliest first', sortBalance: 'Highest amount', sortCreated: 'Recently created', sortStatus: 'Status', sortNumber: 'Payout number',
    prepared: 'Prepared', databaseTotal: 'Database total', visibleRows: 'Visible rows', totalPayout: 'Total payout', selected: 'selected', chooseOwner: 'Choose an owner', chooseProperty: 'Choose a property', chooseEvidence: 'Choose linked evidence', formError: 'Complete all required fields with valid values.', actionError: 'The workflow action could not be completed.', view: 'View details',
  },
  ar: {
    financeControl: 'الرقابة المالية لنظام إدارة العقارات', overview: 'النظرة العامة', charges: 'المطالبات', payments: 'الدفعات', deposits: 'التأمينات', periods: 'الفترات المالية', reconciliation: 'المطابقة', records: 'السجلات',
    statements: 'كشوف الملاك', payouts: 'دفعات الملاك', statementDescription: 'إعداد ومراجعة واعتماد ونشر وتصحيح لقطات مالية ثابتة للملاك.', payoutDescription: 'إعداد دفعات الملاك من الكشوف المنشورة وتسجيل الإرسال والنتيجة بأدلة موثقة.',
    loading: 'جارٍ تحميل السجلات المالية…', error: 'تعذر تحميل مساحة تسويات الملاك.', noRecords: 'لا توجد سجلات تطابق عوامل التصفية.', permission: 'تتطلب إجراءات سير العمل صلاحية إدارة المحاسبة.',
    createStatement: 'إعداد كشف مالك', createPayout: 'إعداد دفعة مالك', search: 'بحث', all: 'الكل', actions: 'الإجراءات', status: 'الحالة', currency: 'العملة', property: 'العقار', owner: 'المالك', sort: 'الترتيب', apply: 'تطبيق التصفية', clear: 'مسح', previous: 'السابق', next: 'التالي', pageOf: 'من',
    period: 'الفترة', revision: 'المراجعة', payoutNumber: 'دفعة المالك', opening: 'الرصيد الافتتاحي', income: 'الدخل', expenses: 'المصروفات', adjustments: 'التسويات', closing: 'الرصيد الختامي', amount: 'المبلغ', documents: 'المستندات الداعمة', history: 'السجل الرقابي', createdBy: 'أعدّه', approvedBy: 'اعتمده', publishedBy: 'نشره', paidBy: 'سجل النتيجة', createdDate: 'تاريخ الإعداد', approvalDate: 'تاريخ الاعتماد', publicationDate: 'تاريخ النشر', submissionDate: 'تاريخ الإرسال', paidDate: 'تاريخ الدفع',
    month: 'شهر الكشف', ownerReference: 'مرجع المالك', notes: 'ملاحظات', managementFee: 'رسوم الإدارة', reserve: 'المبلغ المحتجز', selectStatements: 'الكشوف المنشورة', save: 'حفظ', cancel: 'إلغاء', close: 'إغلاق', upload: 'رفع دليل', documentTitle: 'عنوان المستند', file: 'الملف',
    submitReview: 'إرسال للمراجعة', approve: 'اعتماد', publish: 'نشر', void: 'إبطال', createRevision: 'إنشاء مراجعة', approvePayout: 'اعتماد الدفعة', submitPayout: 'إرسال الدفعة', recordPaid: 'تسجيل نتيجة مدفوعة', recordFailed: 'تسجيل نتيجة فاشلة', retry: 'إعادة المحاولة من المسودة', cancelPayout: 'إلغاء الدفعة', reason: 'السبب', payoutReference: 'مرجع الدفعة الخارجي', evidenceNote: 'ملاحظة دليل طريقة الدفع', providerConfirmed: 'أكد محول الدفع عملية الإرسال', evidenceDocument: 'مستند الدليل',
    makerCheckerStatement: 'لا يمكن لمن أنشأ الكشف اعتماده، ولا يمكن لمن اعتمده نشره.', makerCheckerPayout: 'لا يمكن لمن أعد الدفعة اعتمادها، ولا يمكن لمن اعتمدها إرسالها.', publishReadiness: 'يتطلب النشر فترة مالية مطابقة مغلقة ومستنداً داعماً فعالاً واحداً على الأقل.', paidReadiness: 'تتطلب النتيجة المدفوعة مستند دليل جديداً مرتبطاً ومسجلاً بعد الإرسال.', immutable: 'اللقطات المنشورة وتكوين الدفعات المعتمدة ثابتة. تتم التصحيحات عبر الإبطال والمراجعة أو إعادة محاولة الدفعة.',
    noDocuments: 'لا توجد مستندات داعمة مرتبطة.', noHistory: 'لم تُسجل أحداث رقابية بعد.', noPublishedStatements: 'لا توجد كشوف منشورة مؤهلة لهذا المالك.', linkedPayouts: 'دفعات الملاك المرتبطة',
    sortPeriodLatest: 'الفترة: الأحدث أولاً', sortPeriodEarliest: 'الفترة: الأقدم أولاً', sortBalance: 'أعلى مبلغ', sortCreated: 'الأحدث إنشاءً', sortStatus: 'الحالة', sortNumber: 'رقم الدفعة',
    prepared: 'مُعدّ', databaseTotal: 'إجمالي قاعدة البيانات', visibleRows: 'الصفوف الظاهرة', totalPayout: 'إجمالي الدفعات', selected: 'محدد', chooseOwner: 'اختر مالكاً', chooseProperty: 'اختر عقاراً', chooseEvidence: 'اختر دليلاً مرتبطاً', formError: 'أكمل جميع الحقول المطلوبة بقيم صحيحة.', actionError: 'تعذر إكمال إجراء سير العمل.', view: 'عرض التفاصيل',
  },
} as const;

export function settlementEnumLabel(value: string, language: 'en' | 'ar') {
  const labels: Record<string, { en: string; ar: string }> = {
    APPROVE: { en: 'Approve', ar: 'اعتماد' }, SUBMIT: { en: 'Submit payout', ar: 'إرسال الدفعة' }, RECORD_PAID: { en: 'Record paid result', ar: 'تسجيل نتيجة مدفوعة' }, RECORD_FAILED: { en: 'Record failed result', ar: 'تسجيل نتيجة فاشلة' }, RETRY: { en: 'Retry from draft', ar: 'إعادة المحاولة من المسودة' }, CANCEL: { en: 'Cancel payout', ar: 'إلغاء الدفعة' }, STATUS_TRANSITION: { en: 'Status transition', ar: 'تغيير الحالة' }, GENERATE: { en: 'Statement generated', ar: 'تم إنشاء الكشف' },
    DRAFT: { en: 'Draft', ar: 'مسودة' }, GENERATED: { en: 'Generated', ar: 'مولّد' }, NEEDS_REVIEW: { en: 'Needs review', ar: 'بحاجة للمراجعة' }, APPROVED: { en: 'Approved', ar: 'معتمد' }, PUBLISHED: { en: 'Published', ar: 'منشور' }, VOID: { en: 'Void', ar: 'مبطل' }, PROCESSING: { en: 'Processing', ar: 'قيد المعالجة' }, PAID_MANUAL: { en: 'Paid with evidence', ar: 'مدفوع بدليل' }, FAILED: { en: 'Failed', ar: 'فشل' }, CANCELLED: { en: 'Cancelled', ar: 'ملغى' },
  };
  return labels[value]?.[language] ?? value.replaceAll('_', ' ');
}
