import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

import {
  crmActivityPriorities,
  crmActivityStatuses,
  crmActivityTypes,
  crmAccountTypes,
  crmCommunicationChannels,
  crmContactConsentStatuses,
  crmDealOutcomes,
  crmDeliveryStatuses,
  crmForecastCategories,
  crmPipelineStageTypes,
  crmScoreBands,
  crmScoreTrends,
  crmCommunicationDirections,
  crmCommunicationOutcomes,
  crmContractVersion,
  crmLeadPriorities,
  crmLeadSources,
  crmLeadStatuses,
  workspacePermissionKeys,
  workspaceTypes
} from '../src/modules/crm/contracts';

const literal = (values: readonly string[]) => values.map((value) => `'${value}'`).join(' | ');

function buildOutput() {
  return `/* Generated by backend/scripts/generateCrmContractTypes.ts. Do not edit manually. */\nexport const CRM_CONTRACT_VERSION = '${crmContractVersion}' as const;\nexport type CrmLeadStatus = ${literal(crmLeadStatuses)};\nexport type CrmLeadPriority = ${literal(crmLeadPriorities)};\nexport type CrmLeadSource = ${literal(crmLeadSources)};\nexport type CrmActivityType = ${literal(crmActivityTypes)};\nexport type CrmActivityStatus = ${literal(crmActivityStatuses)};\nexport type CrmActivityPriority = ${literal(crmActivityPriorities)};\nexport type CrmCommunicationDirection = ${literal(crmCommunicationDirections)};\nexport type CrmCommunicationOutcome = ${literal(crmCommunicationOutcomes)};\nexport type WorkspaceType = ${literal(workspaceTypes)};\nexport type WorkspacePermissionKey = ${literal(workspacePermissionKeys)};
export type CrmAccountType = ${literal(crmAccountTypes)};
export type CrmDealOutcome = ${literal(crmDealOutcomes)};
export type CrmForecastCategory = ${literal(crmForecastCategories)};
export type CrmPipelineStageType = ${literal(crmPipelineStageTypes)};
export type CrmScoreBand = ${literal(crmScoreBands)};
export type CrmScoreTrend = ${literal(crmScoreTrends)};
export type CrmCommunicationChannel = ${literal(crmCommunicationChannels)};
export type CrmContactConsentStatus = ${literal(crmContactConsentStatuses)};
export type CrmDeliveryStatus = ${literal(crmDeliveryStatuses)};
`;
}

async function main() {
  const destination = path.resolve(process.cwd(), '../frontend/src/generated/crmContract.ts');
  const output = buildOutput();
  if (process.argv.includes('--check')) {
    const existing = await readFile(destination, 'utf8').catch(() => '');
    if (existing !== output) {
      throw new Error('Generated CRM contract types are out of date. Run npm run contracts:crm:generate.');
    }
    console.log('[lux.om] Generated CRM contract types are current.');
    return;
  }
  await writeFile(destination, output, 'utf8');
  console.log(`[lux.om] Generated ${destination}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
