export const financeCopy = {
  en: {
    close: 'Close dialog',
    overview: 'Finance overview',
    charges: 'Charges',
    payments: 'Payments and allocations',
    deposits: 'Deposits',
    periods: 'Financial periods',
    reconciliation: 'Reconciliation',
    statements: 'Owner statements',
    payouts: 'Owner payouts',
    records: 'Finance records',
    financeControl: 'PMS financial control',
    overviewTitle: 'Charges, allocations, deposits, and owner payouts',
    overviewDescription: 'Structured balances stay separated by currency. Transaction, posting, due, and settlement dates remain distinct.',
    chargeTitle: 'Charges and credit control',
    chargeDescription: 'Create and review draft charges, issue approved amounts, and preserve allocation and adjustment history.',
    paymentTitle: 'Payments and allocations',
    paymentDescription: 'Record confirmed receipts and allocate them safely across issued charges without mixing currencies.',
    createCharge: 'Create draft charge',
    editCharge: 'Edit draft charge',
    createPayment: 'Record payment',
    searchCharges: 'Search charge, property, unit, or tenant',
    searchPayments: 'Search receipt, reference, property, unit, or tenant',
    status: 'Status',
    currency: 'Currency',
    allStatuses: 'All statuses',
    allCurrencies: 'All currencies',
    filter: 'Apply filters',
    sort: 'Sort',
    chargeSortDueLatest: 'Due date: latest first',
    chargeSortDueEarliest: 'Due date: earliest first',
    chargeSortCreated: 'Recently created',
    chargeSortBalance: 'Highest balance',
    paymentSortPaidLatest: 'Transaction date: latest first',
    paymentSortPaidEarliest: 'Transaction date: earliest first',
    paymentSortPosted: 'Recently posted',
    paymentSortAmount: 'Highest amount',
    reset: 'Reset',
    loading: 'Loading finance records…',
    noCharges: 'No charges match this view.',
    noPayments: 'No payments match this view.',
    permissionDenied: 'You can view financial records, but your PMS role cannot post or change them.',
    charge: 'Charge',
    property: 'Property',
    tenantUnit: 'Tenant and unit',
    dueDate: 'Due date',
    total: 'Total',
    balance: 'Balance',
    received: 'Received',
    recordedPayments: 'Recorded payments',
    allocated: 'Allocated',
    available: 'Available',
    transactionDate: 'Transaction date',
    postingDate: 'Posting timestamp',
    settlementDate: 'Settlement timestamp',
    issueDate: 'Issue timestamp',
    actions: 'Actions',
    view: 'View',
    previous: 'Previous',
    next: 'Next',
    pageCount: (from: number, to: number, total: number) => `${from}–${to} of ${total}`,
    saveDraft: 'Save draft',
    saveChanges: 'Save changes',
    issue: 'Issue charge',
    addAdjustment: 'Add adjustment',
    createCreditNote: 'Create credit note',
    voidCharge: 'Void charge',
    allocatePayment: 'Allocate payment',
    paymentAdjustment: 'Refund or adjust payment',
    reverseAllocation: 'Reverse allocation',
    lease: 'Lease',
    selectLease: 'Select lease',
    amount: 'Amount',
    method: 'Payment method',
    reference: 'Reference number',
    notes: 'Notes',
    servicePeriodStart: 'Service period start',
    servicePeriodEnd: 'Service period end',
    lines: 'Charge lines',
    addLine: 'Add line',
    removeLine: 'Remove line',
    category: 'Category',
    description: 'Description',
    quantity: 'Quantity',
    unitAmount: 'Unit amount',
    submit: 'Submit',
    approve: 'Approve',
    apply: 'Apply',
    void: 'Void',
    cancel: 'Cancel',
    reason: 'Reason',
    type: 'Type',
    selectCharges: 'Select issued charges',
    allocationAmount: 'Allocation amount',
    allocationTotal: 'Allocation total',
    noEligibleCharges: 'No issued charges with an outstanding balance are available for this payment currency.',
    incompleteOptions: (shown: number, total: number) => `Showing ${shown} of ${total} eligible records. Refine the workspace data before posting if the target is not visible.`,
    chargeDetails: 'Charge details',
    paymentDetails: 'Payment details',
    linkedRecords: 'Linked records and history',
    adjustmentHistory: 'Adjustments',
    creditHistory: 'Credit notes',
    allocationHistory: 'Allocation history',
    noHistory: 'No history has been recorded.',
    destructiveWarning: 'This action changes financial history and may be irreversible. Review the reason before confirming.',
    issueDescription: 'Issuing locks draft lines and makes the charge eligible for payment allocation.',
    voidDescription: 'Void is allowed only when active allocations have been reversed.',
    successful: 'Financial record updated.',
    outstandingCharges: 'Outstanding charges',
    unallocatedPayments: 'Unallocated payments',
    depositLiabilities: 'Deposit liabilities',
    closedPeriods: 'Closed periods',
    payoutBatches: 'Payout batches',
    count: 'Count',
    manageRequired: 'Accounting management permission is required.',
    formError: 'Review the highlighted financial fields.',
    firstRecordsNotice: (count: number, total: number) => `Loaded ${count} of ${total} leases for selection.`,
  },
  ar: {
    close: 'إغلاق النافذة',
    overview: 'النظرة المالية',
    charges: 'المطالبات المالية',
    payments: 'الدفعات والتخصيصات',
    deposits: 'التأمينات',
    periods: 'الفترات المالية',
    reconciliation: 'المطابقة البنكية',
    statements: 'كشوف الملاك',
    payouts: 'دفعات الملاك',
    records: 'السجلات المالية',
    financeControl: 'الرقابة المالية لنظام إدارة العقارات',
    overviewTitle: 'المطالبات والتخصيصات والتأمينات ومدفوعات الملاك',
    overviewDescription: 'تبقى الأرصدة منفصلة حسب العملة، مع عرض تاريخ المعاملة والترحيل والاستحقاق والتسوية بشكل مستقل.',
    chargeTitle: 'إدارة المطالبات والائتمان',
    chargeDescription: 'أنشئ مسودات المطالبات وراجعها ثم أصدرها مع الحفاظ على سجل التخصيصات والتعديلات.',
    paymentTitle: 'الدفعات والتخصيصات',
    paymentDescription: 'سجّل المقبوضات المؤكدة ووزعها بأمان على المطالبات الصادرة من دون خلط العملات.',
    createCharge: 'إنشاء مسودة مطالبة',
    editCharge: 'تعديل مسودة المطالبة',
    createPayment: 'تسجيل دفعة',
    searchCharges: 'بحث برقم المطالبة أو العقار أو الوحدة أو المستأجر',
    searchPayments: 'بحث بالإيصال أو المرجع أو العقار أو الوحدة أو المستأجر',
    status: 'الحالة',
    currency: 'العملة',
    allStatuses: 'كل الحالات',
    allCurrencies: 'كل العملات',
    filter: 'تطبيق المرشحات',
    sort: 'الترتيب',
    chargeSortDueLatest: 'الاستحقاق: الأحدث أولاً',
    chargeSortDueEarliest: 'الاستحقاق: الأقدم أولاً',
    chargeSortCreated: 'الأحدث إنشاءً',
    chargeSortBalance: 'أعلى رصيد',
    paymentSortPaidLatest: 'المعاملة: الأحدث أولاً',
    paymentSortPaidEarliest: 'المعاملة: الأقدم أولاً',
    paymentSortPosted: 'الأحدث ترحيلاً',
    paymentSortAmount: 'أعلى مبلغ',
    reset: 'إعادة ضبط',
    loading: 'جارٍ تحميل السجلات المالية…',
    noCharges: 'لا توجد مطالبات مطابقة.',
    noPayments: 'لا توجد دفعات مطابقة.',
    permissionDenied: 'يمكنك عرض السجلات المالية، لكن دورك لا يسمح بترحيلها أو تعديلها.',
    charge: 'المطالبة',
    property: 'العقار',
    tenantUnit: 'المستأجر والوحدة',
    dueDate: 'تاريخ الاستحقاق',
    total: 'الإجمالي',
    balance: 'الرصيد',
    received: 'المستلم',
    recordedPayments: 'الدفعات المسجلة',
    allocated: 'المخصص',
    available: 'المتاح',
    transactionDate: 'تاريخ المعاملة',
    postingDate: 'وقت الترحيل',
    settlementDate: 'وقت التسوية',
    issueDate: 'وقت الإصدار',
    actions: 'الإجراءات',
    view: 'عرض',
    previous: 'السابق',
    next: 'التالي',
    pageCount: (from: number, to: number, total: number) => `${from}–${to} من ${total}`,
    saveDraft: 'حفظ المسودة',
    saveChanges: 'حفظ التعديلات',
    issue: 'إصدار المطالبة',
    addAdjustment: 'إضافة تعديل',
    createCreditNote: 'إنشاء إشعار دائن',
    voidCharge: 'إلغاء المطالبة',
    allocatePayment: 'تخصيص الدفعة',
    paymentAdjustment: 'استرداد أو تعديل الدفعة',
    reverseAllocation: 'عكس التخصيص',
    lease: 'عقد الإيجار',
    selectLease: 'اختر عقد الإيجار',
    amount: 'المبلغ',
    method: 'طريقة الدفع',
    reference: 'الرقم المرجعي',
    notes: 'ملاحظات',
    servicePeriodStart: 'بداية فترة الخدمة',
    servicePeriodEnd: 'نهاية فترة الخدمة',
    lines: 'بنود المطالبة',
    addLine: 'إضافة بند',
    removeLine: 'حذف البند',
    category: 'الفئة',
    description: 'الوصف',
    quantity: 'الكمية',
    unitAmount: 'سعر الوحدة',
    submit: 'تنفيذ',
    approve: 'اعتماد',
    apply: 'تطبيق',
    void: 'إلغاء',
    cancel: 'إلغاء',
    reason: 'السبب',
    type: 'النوع',
    selectCharges: 'اختر المطالبات الصادرة',
    allocationAmount: 'مبلغ التخصيص',
    allocationTotal: 'إجمالي التخصيص',
    noEligibleCharges: 'لا توجد مطالبات صادرة برصيد مستحق ومتوافقة مع عملة الدفعة.',
    incompleteOptions: (shown: number, total: number) => `يتم عرض ${shown} من أصل ${total}. قم بتضييق البيانات قبل الترحيل إذا لم يظهر السجل المطلوب.`,
    chargeDetails: 'تفاصيل المطالبة',
    paymentDetails: 'تفاصيل الدفعة',
    linkedRecords: 'السجلات والروابط المرتبطة',
    adjustmentHistory: 'التعديلات',
    creditHistory: 'الإشعارات الدائنة',
    allocationHistory: 'سجل التخصيص',
    noHistory: 'لا يوجد سجل حتى الآن.',
    destructiveWarning: 'يغيّر هذا الإجراء السجل المالي وقد لا يمكن التراجع عنه. راجع السبب قبل التأكيد.',
    issueDescription: 'الإصدار يقفل بنود المسودة ويجعل المطالبة قابلة لتخصيص الدفعات.',
    voidDescription: 'يمكن الإلغاء فقط بعد عكس جميع التخصيصات النشطة.',
    successful: 'تم تحديث السجل المالي.',
    outstandingCharges: 'المطالبات المستحقة',
    unallocatedPayments: 'الدفعات غير المخصصة',
    depositLiabilities: 'التزامات التأمينات',
    closedPeriods: 'الفترات المغلقة',
    payoutBatches: 'دفعات الملاك',
    count: 'العدد',
    manageRequired: 'يلزم إذن إدارة المحاسبة.',
    formError: 'راجع الحقول المالية المحددة.',
    firstRecordsNotice: (count: number, total: number) => `تم تحميل ${count} من أصل ${total} عقدًا للاختيار.`,
  }
} as const;

const arabicFinanceEnums: Record<string, string> = {
  DRAFT: 'مسودة',
  ISSUED: 'صادرة',
  PARTIALLY_PAID: 'مدفوعة جزئياً',
  PAID: 'مدفوعة',
  VOID: 'ملغاة',
  PENDING: 'قيد الانتظار',
  CONFIRMED: 'مؤكدة',
  FAILED: 'فشلت',
  CANCELLED: 'ملغاة',
  REFUNDED: 'مستردة',
  ACTIVE: 'نشط',
  REVERSED: 'معكوس',
  POSTED: 'مرحّل',
  APPROVED: 'معتمد',
  APPLIED: 'مطبق',
  RENT: 'إيجار',
  UTILITIES: 'مرافق',
  SERVICE_CHARGE: 'رسوم خدمات',
  LATE_FEE: 'غرامة تأخير',
  MAINTENANCE: 'صيانة',
  DEPOSIT_DEDUCTION: 'خصم من التأمين',
  DISCOUNT: 'خصم',
  MANUAL_ADJUSTMENT: 'تعديل يدوي',
  OTHER: 'أخرى',
  WRITE_OFF: 'شطب',
  REVERSAL: 'عكس',
  MANUAL: 'يدوي',
  REFUND: 'استرداد',
  CHARGEBACK: 'استرجاع قسري',
  BANK_TRANSFER: 'تحويل بنكي',
  CASH: 'نقداً',
  CHEQUE: 'شيك',
  CARD_MANUAL: 'بطاقة مسجلة يدوياً',
  ONLINE_GATEWAY: 'بوابة دفع إلكترونية',
};

export function formatFinanceEnum(value: string, language: 'en' | 'ar') {
  if (language === 'ar') return arabicFinanceEnums[value] ?? value;
  return value
    .toLowerCase()
    .replaceAll('_', ' ')
    .replace(/(^|\s)\S/g, (character) => character.toUpperCase());
}

export function financeLocale(language: 'en' | 'ar') {
  return language === 'ar' ? 'ar-OM' : 'en-OM';
}

export function formatFinanceMoney(value: string | number, currency: string, language: 'en' | 'ar') {
  const amount = Number(value);
  if (!Number.isFinite(amount)) return `— ${currency}`;
  try {
    return new Intl.NumberFormat(financeLocale(language), { style: 'currency', currency }).format(amount);
  } catch {
    return `${amount.toLocaleString(financeLocale(language), { minimumFractionDigits: 2, maximumFractionDigits: 3 })} ${currency}`;
  }
}

export function formatFinanceDate(value: string | null | undefined, language: 'en' | 'ar', withTime = false) {
  if (!value) return '—';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return '—';
  return new Intl.DateTimeFormat(financeLocale(language), withTime
    ? { dateStyle: 'medium', timeStyle: 'short' }
    : { dateStyle: 'medium' }
  ).format(date);
}

export function createFinanceIdempotencyKey(prefix: string) {
  const random = typeof crypto !== 'undefined' && 'randomUUID' in crypto
    ? crypto.randomUUID()
    : `${Date.now()}-${Math.random().toString(16).slice(2)}`;
  return `${prefix}-${random}`;
}
